# Generated by Django 5.2.2 on 2025-06-14 10:32

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TK', 'Tanks'), ('HL', 'Healers'), ('DD', 'DD'), ('MC', 'Merchants'), ('GM', 'Guild masters'), ('QG', 'Quest givers'), ('BS', 'Blacksmiths'), ('TN', 'Tanners'), ('PM', 'Potion makers'), ('SM', 'Spellmasters')], default='TK')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.advertisement')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.reply')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='replies',
            field=models.ManyToManyField(through='ad.AdvertisementReply', to='ad.reply'),
        ),
    ]
