# Generated by Django 5.2.2 on 2025-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_user_authentication_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authentication_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
