# Generated by Django 5.2.2 on 2025-06-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='replies',
        ),
        migrations.AddField(
            model_name='reply',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ad.advertisement'),
        ),
        migrations.DeleteModel(
            name='AdvertisementReply',
        ),
    ]
