# Generated by Django 5.2.2 on 2025-06-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_remove_advertisement_replies_reply_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='reply',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
